services:
  kafka:
    image: 'bitnami/kafka:4.0.0'
    container_name: kafka
    ports:
      - "9094:9094"
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092,EXTERNAL://host.docker.internal:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - BITNAMI_DEBUG=yes
    # volumes:
    #   - kafka_data:/bitnami/kafka
    networks:
      - kafka-net

  akhq:
    image: tchiotludo/akhq:0.25.1
    container_name: akhq
    ports:
      - "9999:8080"
    environment:
      AKHQ_CONFIGURATION: |+
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "host.docker.internal:9092"

    networks:
      - kafka-net

  command-mysql:
    image: mysql:9.2
    container_name: command-mysql
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: $COMMAND_DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    networks:
      - $DOCKER_NET
    ports:
      - "3306:3306"
  query-mysql:
    image: mysql:9.2
    container_name: query-mysql
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: $QUERY_DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    networks:
      - $DOCKER_NET
    ports:
      - "3307:3306"
networks:
  product-net:
  kafka-net:
