/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.bruce_mig.cqrs.payload;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProductEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8170846343585454234L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductEvent\",\"namespace\":\"com.github.bruce_mig.cqrs.payload\",\"fields\":[{\"name\":\"eventType\",\"type\":\"string\"},{\"name\":\"productDto\",\"type\":{\"type\":\"record\",\"name\":\"ProductDto\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"price\",\"type\":\"double\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProductEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence eventType;
  private com.github.bruce_mig.cqrs.payload.ProductDto productDto;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductEvent() {}

  /**
   * All-args constructor.
   * @param eventType The new value for eventType
   * @param productDto The new value for productDto
   */
  public ProductEvent(java.lang.CharSequence eventType, com.github.bruce_mig.cqrs.payload.ProductDto productDto) {
    this.eventType = eventType;
    this.productDto = productDto;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventType;
    case 1: return productDto;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventType = (java.lang.CharSequence)value$; break;
    case 1: productDto = (com.github.bruce_mig.cqrs.payload.ProductDto)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public java.lang.CharSequence getEventType() {
    return eventType;
  }


  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(java.lang.CharSequence value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'productDto' field.
   * @return The value of the 'productDto' field.
   */
  public com.github.bruce_mig.cqrs.payload.ProductDto getProductDto() {
    return productDto;
  }


  /**
   * Sets the value of the 'productDto' field.
   * @param value the value to set.
   */
  public void setProductDto(com.github.bruce_mig.cqrs.payload.ProductDto value) {
    this.productDto = value;
  }

  /**
   * Creates a new ProductEvent RecordBuilder.
   * @return A new ProductEvent RecordBuilder
   */
  public static com.github.bruce_mig.cqrs.payload.ProductEvent.Builder newBuilder() {
    return new com.github.bruce_mig.cqrs.payload.ProductEvent.Builder();
  }

  /**
   * Creates a new ProductEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductEvent RecordBuilder
   */
  public static com.github.bruce_mig.cqrs.payload.ProductEvent.Builder newBuilder(com.github.bruce_mig.cqrs.payload.ProductEvent.Builder other) {
    if (other == null) {
      return new com.github.bruce_mig.cqrs.payload.ProductEvent.Builder();
    } else {
      return new com.github.bruce_mig.cqrs.payload.ProductEvent.Builder(other);
    }
  }

  /**
   * Creates a new ProductEvent RecordBuilder by copying an existing ProductEvent instance.
   * @param other The existing instance to copy.
   * @return A new ProductEvent RecordBuilder
   */
  public static com.github.bruce_mig.cqrs.payload.ProductEvent.Builder newBuilder(com.github.bruce_mig.cqrs.payload.ProductEvent other) {
    if (other == null) {
      return new com.github.bruce_mig.cqrs.payload.ProductEvent.Builder();
    } else {
      return new com.github.bruce_mig.cqrs.payload.ProductEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductEvent>
    implements org.apache.avro.data.RecordBuilder<ProductEvent> {

    private java.lang.CharSequence eventType;
    private com.github.bruce_mig.cqrs.payload.ProductDto productDto;
    private com.github.bruce_mig.cqrs.payload.ProductDto.Builder productDtoBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.bruce_mig.cqrs.payload.ProductEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventType)) {
        this.eventType = data().deepCopy(fields()[0].schema(), other.eventType);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productDto)) {
        this.productDto = data().deepCopy(fields()[1].schema(), other.productDto);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasProductDtoBuilder()) {
        this.productDtoBuilder = com.github.bruce_mig.cqrs.payload.ProductDto.newBuilder(other.getProductDtoBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing ProductEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.bruce_mig.cqrs.payload.ProductEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventType)) {
        this.eventType = data().deepCopy(fields()[0].schema(), other.eventType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productDto)) {
        this.productDto = data().deepCopy(fields()[1].schema(), other.productDto);
        fieldSetFlags()[1] = true;
      }
      this.productDtoBuilder = null;
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventType() {
      return eventType;
    }


    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public com.github.bruce_mig.cqrs.payload.ProductEvent.Builder setEventType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public com.github.bruce_mig.cqrs.payload.ProductEvent.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productDto' field.
      * @return The value.
      */
    public com.github.bruce_mig.cqrs.payload.ProductDto getProductDto() {
      return productDto;
    }


    /**
      * Sets the value of the 'productDto' field.
      * @param value The value of 'productDto'.
      * @return This builder.
      */
    public com.github.bruce_mig.cqrs.payload.ProductEvent.Builder setProductDto(com.github.bruce_mig.cqrs.payload.ProductDto value) {
      validate(fields()[1], value);
      this.productDtoBuilder = null;
      this.productDto = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productDto' field has been set.
      * @return True if the 'productDto' field has been set, false otherwise.
      */
    public boolean hasProductDto() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'productDto' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.github.bruce_mig.cqrs.payload.ProductDto.Builder getProductDtoBuilder() {
      if (productDtoBuilder == null) {
        if (hasProductDto()) {
          setProductDtoBuilder(com.github.bruce_mig.cqrs.payload.ProductDto.newBuilder(productDto));
        } else {
          setProductDtoBuilder(com.github.bruce_mig.cqrs.payload.ProductDto.newBuilder());
        }
      }
      return productDtoBuilder;
    }

    /**
     * Sets the Builder instance for the 'productDto' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.github.bruce_mig.cqrs.payload.ProductEvent.Builder setProductDtoBuilder(com.github.bruce_mig.cqrs.payload.ProductDto.Builder value) {
      clearProductDto();
      productDtoBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'productDto' field has an active Builder instance
     * @return True if the 'productDto' field has an active Builder instance
     */
    public boolean hasProductDtoBuilder() {
      return productDtoBuilder != null;
    }

    /**
      * Clears the value of the 'productDto' field.
      * @return This builder.
      */
    public com.github.bruce_mig.cqrs.payload.ProductEvent.Builder clearProductDto() {
      productDto = null;
      productDtoBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductEvent build() {
      try {
        ProductEvent record = new ProductEvent();
        record.eventType = fieldSetFlags()[0] ? this.eventType : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (productDtoBuilder != null) {
          try {
            record.productDto = this.productDtoBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("productDto"));
            throw e;
          }
        } else {
          record.productDto = fieldSetFlags()[1] ? this.productDto : (com.github.bruce_mig.cqrs.payload.ProductDto) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductEvent>
    READER$ = (org.apache.avro.io.DatumReader<ProductEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventType);

    this.productDto.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventType = in.readString(this.eventType instanceof Utf8 ? (Utf8)this.eventType : null);

      if (this.productDto == null) {
        this.productDto = new com.github.bruce_mig.cqrs.payload.ProductDto();
      }
      this.productDto.customDecode(in);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventType = in.readString(this.eventType instanceof Utf8 ? (Utf8)this.eventType : null);
          break;

        case 1:
          if (this.productDto == null) {
            this.productDto = new com.github.bruce_mig.cqrs.payload.ProductDto();
          }
          this.productDto.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










